apiVersion: v1
kind: Endpoints
metadata:
  name: canal-metrics
  labels:
    k8s-app: canal-metrics
subsets:
- addresses:
  - ip: 172.18.20.229
  ports:
  - name: canal-metrics-port-01
    port: 11112
    protocol: TCP
- addresses:
  - ip: 172.18.20.229
  ports:
  - name: canal-metrics-port-02
    port: 11122
    protocol: TCP

