{
 "title": "Canal Dashboard",
 "tags": [ "canal" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "destination",
    "label": "destination",
    "query": "label_values(canal_instance, destination)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(canal_instance,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Instance status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Basic",
   "type": "graph",
   "description": "Canal instance 基本信息。",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "canal_instance{destination=~\"$destination\",instance=~\"$instance\"}",
     "legendFormat": "Destination: {{destination}}(instance:{{instance}})"
    },
    {
     "expr": "canal_instance_parser_mode{destination=~\"$destination\",instance=~\"$instance\"}",
     "legendFormat": "Parallel parser: {{parallel}}(instance:{{instance}})"
    },
    {
     "expr": "canal_instance_store{destination=~\"$destination\",instance=~\"$instance\"}",
     "legendFormat": "Batch mode: {{batchMode}}(instance:{{instance}})"
    },
    {
     "expr": "canal_instance_store{destination=~\"$destination\",instance=~\"$instance\"}",
     "legendFormat": "Buffer size: {{size}}(instance:{{instance}})"
    }
   ]
  },
  {
   "title": "Network bandwith",
   "type": "graph",
   "description": "Canal instance 网络带宽占用。\ninbound: 读取MySQL binlog.\noutbound: 对Client端传输格式化binlog.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(canal_instance_received_binlog_bytes{destination=~\"$destination\",instance=~\"$instance\", parser=\"0\"}[2m]) / 1024",
     "legendFormat": "inbound(instance:{{instance}})"
    },
    {
     "expr": "rate(canal_instance_client_bytes{destination=~\"$destination\",instance=~\"$instance\"}[2m]) / 1024",
     "legendFormat": "outbound(instance:{{instance}})"
    },
    {
     "expr": "rate(canal_instance_received_binlog_bytes{destination=~\"$destination\",instance=~\"$instance\", parser=\"1\"}[2m]) / 1024",
     "legendFormat": "inbound-1(instance:{{instance}})"
    },
    {
     "expr": "rate(canal_instance_received_binlog_bytes{destination=~\"$destination\",instance=~\"$instance\", parser=\"2\"}[2m]) / 1024",
     "legendFormat": "inbound-2(instance:{{instance}})"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "graph",
   "description": "master: Canal server相对于MySQL master的延时。通过master heartbeat机制能刷新idle状态下的延时。\nput: store put操作的时间点为基准。\nget: client get操作的时间点为基准。\nack:  client ack操作的时间点为基准。",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "canal_instance_traffic_delay{destination=~\"$destination\",instance=~\"$instance\"} / 1000",
     "legendFormat": "master(instance:{{instance}})"
    },
    {
     "expr": "canal_instance_put_delay{destination=~\"$destination\",instance=~\"$instance\"} / 1000",
     "legendFormat": "put(instance:{{instance}})"
    },
    {
     "expr": "canal_instance_get_delay{destination=~\"$destination\",instance=~\"$instance\"} / 1000",
     "legendFormat": "get(instance:{{instance}})"
    },
    {
     "expr": "canal_instance_ack_delay{destination=~\"$destination\",instance=~\"$instance\"} / 1000",
     "legendFormat": "ack(instance:{{instance}})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "graph",
   "description": "sink线程blocking占比；dump线程blocking占比(仅parallel mode)。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(rate(canal_instance_publish_blocking_time{destination=~\"$destination\",instance=~\"$instance\", parser=\"0\"}[2m]), 1000) / 10",
     "legendFormat": "dump(instance:{{instance}})"
    },
    {
     "expr": "clamp_max(rate(canal_instance_sink_blocking_time{destination=~\"$destination\",instance=~\"$instance\"}[2m]), 1000) / 10",
     "legendFormat": "sink(instance:{{instance}})"
    },
    {
     "expr": "clamp_max(rate(canal_instance_publish_blocking_time{destination=~\"$destination\",instance=~\"$instance\", parser=\"1\"}[2m]), 1000) / 10",
     "legendFormat": "dump-1(instance:{{instance}})"
    },
    {
     "expr": "clamp_max(rate(canal_instance_publish_blocking_time{destination=~\"$destination\",instance=~\"$instance\", parser=\"2\"}[2m]), 1000) / 10",
     "legendFormat": "dump-2(instance:{{instance}})"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TPS(table rows)",
   "type": "graph",
   "description": "Instance处理binlog的TPS(以master变更行数table rows为基准计算)。\nput: put操作TPS。\nget: get操作TPS。\nack: ack操作TPS。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(canal_instance_put_rows{destination=~\"$destination\",instance=~\"$instance\"}[2m])",
     "legendFormat": "put(instance:{{instance}})"
    },
    {
     "expr": "rate(canal_instance_get_rows{destination=~\"$destination\",instance=~\"$instance\"}[2m])",
     "legendFormat": "get(instance:{{instance}})"
    },
    {
     "expr": "rate(canal_instance_ack_rows{destination=~\"$destination\",instance=~\"$instance\"}[2m])",
     "legendFormat": "ack(instance:{{instance}})"
    }
   ]
  },
  {
   "title": "TPS(MySQL transaction)",
   "type": "graph",
   "description": "Canal instance 处理binlog的TPS，以MySQL transaction为单位计算。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(canal_instance_transactions{destination=~\"$destination\",instance=~\"$instance\"}[2m])",
     "legendFormat": "transactions(instance:{{instance}})"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Client requests",
   "type": "graph",
   "description": "Canal instance接收到的请求统计，结果按packet type分类。",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "canal_instance_client_packets{destination=~\"$destination\",instance=~\"$instance\"}",
     "legendFormat": "{{packetType}}(instance:{{instance}})"
    }
   ]
  },
  {
   "title": "Client QPS",
   "type": "graph",
   "description": "client 请求的GET与ACK包的QPS。",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(canal_instance_client_packets{destination=~\"$destination\",instance=~\"$instance\",packetType=\"GET\"}[2m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(canal_instance_client_packets{destination=~\"$destination\",instance=~\"$instance\",packetType=\"CLIENTACK\"}[2m])",
     "legendFormat": "ACK"
    }
   ]
  },
  {
   "title": "Empty packets",
   "type": "graph",
   "description": "server响应GET请求，但返回空包的占比。",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(canal_instance_client_empty_batches{destination=~\"$destination\",instance=~\"$instance\"}[2m])",
     "legendFormat": "empty"
    },
    {
     "expr": "rate(canal_instance_client_packets{destination=~\"$destination\",instance=~\"$instance\", packetType=\"GET\"}[2m])",
     "legendFormat": "nonempty"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "description": "Canal client 请求响应时间的概况。",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(canal_instance_client_request_latency_bucket{destination=~\"$destination\",instance=~\"$instance\"}[2m])",
     "legendFormat": "{{le}}ms"
    }
   ]
  },
  {
   "title": "Store remain events",
   "type": "graph",
   "description": "Canal instance ringbuffer内未释放的events数量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "canal_instance_store_produce_seq{destination=~\"$destination\",instance=~\"$instance\"} - canal_instance_store_consume_seq{destination=~\"$destination\",instance=~\"$instance\"}",
     "legendFormat": "events(instance:{{instance}})"
    }
   ]
  },
  {
   "title": "Store remain mem",
   "type": "graph",
   "description": "Canal instance ringbuffer 内未释放events占用内存。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(canal_instance_store_produce_mem{destination=~\"$destination\",instance=~\"$instance\"} - canal_instance_store_consume_mem{destination=~\"$destination\",instance=~\"$instance\"}) / 1024",
     "legendFormat": "memsize(instance:{{instance}})"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } }
 ]
}