{
 "title": "SpringBoot Applications Http Request Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(job)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Rate Total Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m]))",
     "legendFormat": "HTTP Rate Total Count"
    }
   ]
  },
  {
   "title": "HTTP Rate Per APP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (job)"
    }
   ]
  },
  {
   "title": "HTTP Rate By Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (method)"
    }
   ]
  },
  {
   "title": "HTTP Rate By Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "HTTP Rate By URI",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (uri)"
    }
   ]
  },
  {
   "title": "HTTP Rate By ResultCode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (result_code)"
    }
   ]
  },
  {
   "title": "HTTP Rate By Exception",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (exception)"
    }
   ]
  },
  {
   "title": "HTTP Request Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (job,uri,status,method,exception,outcome,result_code,result_msg)"
    }
   ]
  }
 ]
}