apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-metrics
  labels:
    k8s-app: nginx-ingress-controller-metrics
  namespace: kube-system
spec:
  ports:
  - name: prometheus
    port: 10254
    targetPort: 10254
    protocol: TCP
  selector:
    app: ingress-nginx
  type: ClusterIP
