apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller-metrics
spec:
  endpoints:
  - interval: 15s
    port: prometheus
    #path: /metrics
    honorLabels: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      k8s-app: nginx-ingress-controller-metrics
