apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-metrics
  labels:
    k8s-app: nginx-ingress-controller-metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: nginx-ingress-controller-metrics-port
      port: 10254
      targetPort: 10254
      protocol: TCP
