apiVersion: v1
kind: Endpoints
metadata:
  name: nginx-ingress-controller-metrics
  labels:
    k8s-app: nginx-ingress-controller-metrics
subsets:
- addresses:
  - ip: 10.0.0.99
  - ip: 10.0.0.95
  - ip: 10.0.0.93
  - ip: 10.0.0.91
  - ip: 10.0.0.90
  - ip: 10.0.0.89
  - ip: 10.0.0.88
  - ip: 10.0.0.87
  - ip: 10.0.0.77
  - ip: 10.0.0.100
  - ip: 10.0.0.101
  ports:
  - name: nginx-ingress-controller-metrics-port
    port: 10254
    protocol: TCP
