apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    k8s-app: nginx-exporter
spec:
  endpoints:
  - interval: 15s
    port: nginx-exporter
    #path: /metrics
    honorLabels: true
    relabelings:
      - action: replace
        separator: ;
        sourceLabels: [ __meta_kubernetes_pod_label_target_instance_id ]
        regex: (.*)
        targetLabel: instance
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      k8s-app: nginx-exporter
