apiVersion: v1
kind: Service
metadata:
  name: outside-node-exporter
  labels:
    k8s-app: outside-node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: outside-node-exporter-port
      port: 9102
      targetPort: 9102
      protocol: TCP
  #selector:
  #  k8s-app: outside-node-exporter
