apiVersion: v1
kind: Endpoints
metadata:
  name: outside-node-exporter
  labels:
    k8s-app: outside-node-exporter
subsets:
- addresses:
  - ip: 172.18.21.252
  ports:
  - name: outside-node-exporter-port
    port: 9102
    protocol: TCP
