apiVersion: v1
kind: Service
metadata:
  name: canal-metrics
  labels:
    k8s-app: canal-metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: canal-metrics-port
      port: 11112
      targetPort: 11112
      protocol: TCP
  #selector:
  #  k8s-app: canal-metrics
