apiVersion: v1
kind: Service
metadata:
  labels:
    app: pmm-server
  name: pmm-server
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  #- name: https
  #  port: 443
  #  targetPort: https
  selector:
    app: pmm-server
