apiVersion: v1
kind: Endpoints
metadata:
  name: outside-node-exporter
  labels:
    k8s-app: outside-node-exporter
subsets:
- addresses:
  - ip: 10.0.0.159
  - ip: 10.0.0.2
  - ip: 10.0.0.3
  ports:
  - name: outside-node-exporter-port
    port: 9102
    protocol: TCP
